// AUTO-GENERATED by scripts/rename-models.mjs — do not edit by hand.
// Maps WooCommerce product id → Goya Mediterranean model name.
// Regenerate with:  node scripts/rename-models.mjs
export const MODEL_NAMES: Record<number, string> = {
  237598: "Veloz", // G 218 · Drive
  237602: "Azahar", // G 221 · City
  237605: "Ronda", // G 217 · Coast
  237606: "Rumbo", // G 214 · City
  238105: "Jazmín", // G 55004 CZ · Coast
  238829: "Vuelo", // G 55007 · Coast
  238836: "Nerja", // G 8004 · Weekend
  239041: "Deriva", // G 55T001 · City
  239046: "Nómada", // G 55T002 · City
  243658: "Dalia", // G 0901S · Coast
  243742: "Amapola", // G 15217 · Coast
  243836: "Errante", // G 1014 C8 · City
  243848: "Camelia", // G 942117 · Coast
  243863: "Tarifa", // G 942115 · Weekend
  243868: "Magnolia", // G 2618 C4 · City
  243869: "Violeta", // G 2618 C2 · City
  243870: "Malva", // G 2618 C1 · City
  243871: "Denia", // G 2615 C1 · City
  243876: "Lila", // G 2611 C2 · Coast
  243881: "Flor", // G 2603 C1 · Coast
  243882: "Adelfa", // G 2622 C4 · City
  243883: "Buganvilla", // G 2622 C3 · City
  243884: "Mirto", // G 2622 C2 · City
  243885: "Lavanda", // G 2622 C1 · City
  243886: "Espliego", // okulary korekcyjne G 2619 C4 · City
  243887: "Oliva", // okulary korekcyjne G 2619 C3 · City
  243888: "Palma", // G 2652 C3 · Coast
  243898: "Retama", // G 2637 · Coast
  243903: "Jara", // okulary korekcyjne G 2635 C4 · Coast
  243904: "Tomillo", // okulary korekcyjne G 2635 C3 · Coast
  243905: "Romero", // okulary korekcyjne G 2635 C1 · Coast
  243911: "Salvia", // okulary korekcyjne G 2672 C1 · Coast
  243912: "Menta", // G 2659 C4 · City
  243913: "Laurel", // G 2659 C1 · City
  243918: "Nardo", // okulary korekcyjne G 2657 C2 · Coast
  243919: "Azucena", // G 2655 C1 · Coast
  243924: "Luna", // G 2716 C1 · City
  243929: "Estrella", // okulary korekcyjne G 2714 C4 · City
  243931: "Nube", // G 2714 C1 · City
  243936: "Cielo", // okulary korekcyjne G 2694 C2 · Weekend
  243941: "Astro", // okulary korekcyjne G 2694 C1 · Weekend
  243946: "Cometa", // G 2682 · Coast
  243956: "Aura", // okulary korekcyjne G 2742 C4 · City
  243957: "Alma", // okulary korekcyjne G 2742 C2 · City
  243963: "Lira", // G 2740 · City
  243968: "Diva", // G 2717 C4 · City
  243973: "Jávea", // G 89087 C3 · Weekend
  243978: "Begur", // okulary korekcyjne G 89087 C2 · Weekend
  243989: "Formentera", // G 89083 · City
  243994: "Altea", // G 89020 · City
  244009: "Musa", // GH 5001 · Coast
  244019: "Trayecto", // DC 8039 · City
  244029: "Ninfa", // GL 6503 C3 · Coast
  244035: "Ímpetu", // GK 7107 · City
  244045: "Gala", // GK 7078 · Coast
  244050: "Serena", // RD 396 C2 · Coast
  244056: "Gracia", // LF 81209 C4 · City
  244057: "Brío", // LB 8936 C5 · City
  244058: "Raudo", // LB 8936 C3 · City
  244063: "Dulce", // LA 9910 C4 · City
  244068: "Cabo", // GM 7080 · City
  244078: "Regata", // M 9010 · City
  244093: "Bella", // M 9004 · Coast
  244098: "Celeste", // M 8209 · Coast
  244103: "Neblina", // RD 150 C4 · Coast
  244104: "Calma", // MA 3021 C3 · Coast
  244247: "Sosiego", // MA 3021 C2 · Coast
  244248: "Remanso", // RD 654 C3 · Coast
  244253: "Sereno", // RD 396 C3 · Coast
  244254: "Calpe", // okulary korekcyjne TJ 032 C3 · City
  244255: "Jade", // T 1013 C6 · Weekend
  244260: "Timón", // SD 1368 C8 · City
  244270: "Ópalo", // G 93234 C2 · Coast
  244275: "Turquesa", // G 93212 C1 · City
  244290: "Esmeralda", // G 93205 · Coast
  244295: "Proa", // G 94313 · City
  244300: "Ancla", // G 94312 C1 · City
  244315: "Chispa", // G 93304 · Weekend
  244332: "Mojácar", // G 94411 · Weekend
  244347: "Cuarzo", // G 94402 · Coast
  244356: "Comillas", // G 94319 C2 · City
  244363: "Marfil", // G 94317 C2 · City
  244376: "Llanes", // G 95544 C3 · Coast
  244389: "Bruma", // G 95541 · City
  244394: "Roble", // G 1478 C2 · City
  244404: "Cedro", // G 96302 · City
  244414: "Sóller", // G 96301 · Coast
  244419: "Cadaqués", // G 95551 · Coast
  244424: "Pino", // G 96303 · City
  244429: "Duende", // G 93305 · Weekend
  244447: "Azabache", // G 96514S C21 · Weekend
  244458: "Marbella", // G 96512S · City
  244579: "Cádiz", // G1904 · Coast
  244590: "Ibiza", // G1835 C3 · Coast
  244619: "Menorca", // G100 · Coast
  244629: "Mallorca", // G1926 C1 · Coast
  244646: "Almería", // G1923 C1 · Coast
  244657: "Sitges", // G1921 · Coast
  244692: "Tossa", // G1905 C1 · Coast
  244983: "Olmo", // G 55006 · Coast
  245019: "Fresno", // G 55010 · Coast
  245113: "Risco", // G 55016 · Coast
  245155: "Monte", // G 55017 · Coast
  245199: "Sierra", // G 55032 · Coast
  245226: "Halcón", // G 55042 · City
  245250: "Lince", // G 9496 · City
  245316: "Ébano", // G CP3718 · City
  245340: "Bronce", // G CP3717 · City
  245367: "Cobre", // G 6230 R · Weekend
  245396: "Canela", // G 6232 · Coast
  245445: "Peñíscola", // G 7107 · Coast
  245464: "Almendra", // G 205 · Coast
  245493: "Bravo", // G 199 · Coast
  245502: "Avellana", // G 196 BR · Coast
  245531: "Trigo", // G 195 · Coast
  245540: "Grana", // G 190 CZ · Coast
  245548: "Carmín", // G 191 BR · Coast
  245561: "Getaria", // G 193 CZ · City
  245583: "Noble", // G 189 · Drive
  245591: "Zahara", // G 188 GR · Coast
  245657: "Añil", // G 187 · Coast
  245673: "Malaquita", // G 186 · Coast
  245694: "Miel", // G 185 · Coast
  245701: "Ocre", // G 184 C · Coast
  245722: "Brisa", // G 183 · Weekend
  245743: "Aire", // G 182 · Coast
  245765: "Hidalgo", // G 180 GR · City
  245772: "Corsario", // G 177 CZ · Drive
  245789: "Timonel", // G 176 · Drive
  245801: "Norte", // G 175 CZ · Drive
  245833: "Céfiro", // G 172 · City
  245865: "Levante", // G 171 · Weekend
  245901: "Duero", // G 166 GR · City
  245915: "Poniente", // G 164 · City
  253055: "Mistral", // G 146 · Weekend
  253071: "Lucero", // G 148 · Weekend
  253086: "Conil", // G 149 · City
  253100: "Ámbar", // G 150 GR C · City
  253109: "Sirena", // G 151 · City
  253125: "Ebro", // G 153 · Weekend
  253140: "Perla", // G 154 CZ · Weekend
  253158: "Tajo", // G 157 BR · Weekend
  253166: "Frigiliana", // G 160 · City
  253171: "Mundaka", // G 161 · City
  253175: "Tulum", // G 162 · City
  253178: "Marina", // G 170 · City
  253506: "Tramontana", // G 210 · Coast
  253763: "Duna", // G 201 CZ · Drive
  253959: "Portofino", // G 21611 CZ · Coast
  253966: "Libre", // G 21609 · Coast
  255981: "Fiesta", // PG 3026 · Coast
  256018: "Verano", // CP 8803 · Coast
  256037: "Siesta", // CP 8802 · Coast
  256054: "Feria", // CP 806639 · Coast
  256082: "Sarao", // CP 806632 · Coast
  256121: "Arena", // CJ 1943 · City
  256172: "Verbena", // A 0736 · Weekend
  256193: "Luz", // A 0711 · City
  256209: "Sol", // A 0710 · City
  256227: "Rayo", // A 0709 CZ · City
  334136: "Alba", // G 55004 BR · Coast
  334538: "Mar", // G 55001 BR · City
  334571: "Marea", // G 55001 GR · City
  334574: "Oleaje", // G 55001 CZ · City
  334580: "Costa", // G 55015 BR · City
  334596: "Cala", // G 55015 GR · City
  334606: "Bahía", // G 55015 CZ · City
  334688: "Faro", // G 55012 GR · City
  334708: "Vela", // G 55012 CZ · City
  337384: "Coral", // G 55021 CZ · City
  337402: "Aurora", // G 55029 CZ · Coast
  337412: "Ocaso", // G 55029 GR · Coast
  337427: "Solano", // G 55051 CZ · Coast
  337436: "Claro", // G 55051 GR · Coast
  337482: "Destello", // G 55054 CZ · Coast
  337493: "Fulgor", // G 55054 GR · Coast
  421549: "Lumbre", // okulary przeciwsłoneczne z filtrem UV- G 1000 BR · City
};
